### PR TITLE
Patch 3

### PR DESCRIPTION
**Pull request by Coligad**

### CODE REVIEW

**Comment by Theawesomeboophis** [comment]
@Coligad There are merge conflicts again.

**Comment by Coligad** [comment]
Duplicate of #

> @Coligad There are merge conflicts again.

Do you know how to fix this? since this is the first time I've have this problem.

**Comment by Theawesomeboophis** [comment]
There are also merge conflicts with the previous pr but I am not sure what the cause is or how to fix it. Can you pull the changes from master into the branches, that should hopefully fix it.

**Comment by Coligad** [comment]
by

**Comment by Coligad** [comment]
IMG_20230903_140350

should I do this to fix this issue?

**Comment by Theawesomeboophis** [comment]
I don't know how to fix this but don't press the red button as it will delete all of your changes

**Comment by Coligad** [comment]
> There are also merge conflicts with the previous pr but I am not sure what the cause is or how to fix it. Can you pull the changes from master into the branches, that should hopefully fix it if it's what I think it is that's causing the error.


IMG_20230904_172232
Is this what you referred to?

**Comment by Theawesomeboophis** [comment]
No, PR from my master to your branch, that should account for changes

**Comment by Theawesomeboophis** [comment]
Previous Pr was fixed by Lylesy, his reccomendation is to pull the master into your branch and redo the Pr after your fork is updated to current unpacked.

**Comment by Coligad** [comment]
> Previous Pr was fixed by Lylesy, his reccomendation is to pull the master into your branch and redo the Pr after your fork is updated to current unpack.

How do I do that?

**Comment by Theawesomeboophis** [comment]
You press the button to pull changes from master, which should appear above the files, but save copies of the files you're changing, and then add the additions after the pull, and lint and that should fix it.

**Comment by Theawesomeboophis** [comment]
Save your changes somewhere else ( such as on hard drive) before you hit the red button tho, if you hit the red button without saving the changes somewhere, you're work will be deleted.

**Comment by Coligad** [comment]
> You press the button to pull changes from master, which should appear above the files, but save copies of the files you're changing, and then add the additions after the pull, and lint and that should fix it.

which button are you referring to?

**Comment by Theawesomeboophis** [comment]
Save your changes somewhere else, then press the discard button and readd the changes afterwards.

**Pull request closed without merging**
